---@class Globals
---@field c number
---@field q number
---@field r number
---@field vertRepeater number
---@field gCurrentRenderCamera number
---@field gRenderCameraTilePos point
---@field gRenderCameraPixelPos point
---@field afterEffects number
---@field closestProp number
---@field colr color
---@field daddyCorruptionHoles table
---@field dptsL table
---@field fogDptsL table
---@field effectIn3D number
---@field effectSeed number
---@field gAnyDecals number
---@field gCurrentlyRenderingTrash number
---@field gDecalColors table
---@field gdLayer string
---@field gEffects table
---@field gCustomEffects table
---@field gESoftProp number
---@field gLastImported string
---@field gLastImportedImage Image
---@field glgtimgQuad table
---@field gProps table
---@field gRenderTrashProps table
---@field gTiles table
---@field gTinySignsDrawn number
---@field gTrashPropOptions table
---@field gViewRender number
---@field keepLooping number
---@field pos point
---@field propsToRender table
---@field slagHoles table
---@field solidMtrx table
---@field tileSetIndex table
---@field tm number
---@field wireBunchSav table
---@field gSaveProps table
---@field INT_EXIT string v Community additions
---@field INT_EXRD string
---@field DRInternalList table
---@field DRFirstTileCat number
---@field DRLastMatCat number
---@field RandomMetals_allowed table
---@field RandomMetals_grabTiles table
---@field ChaoticStone2_needed table
---@field DRRandomMetal_needed table
---@field SmallMachines_grabTiles table
---@field SmallMachines_forbidden table
---@field RandomMachines_forbidden table
---@field RandomMachines_grabTiles table
---@field RandomMachines2_forbidden table
---@field RandomMachines2_grabTiles table
---@field gDRMatFixes number
---@field gDRInvI number
---@field grimeActive number
---@field grimeOnGradients number
---@field bkgFix number
---@field gRRSpreadsMore number
---@field slimeFxt number
---@field showConstrols number
---@field rndDisF number
---@field DRPxl Image
---@field GL_ptPos number
---@field GL_drPos number
---@field gCustomLights table
---@field gFSLastTm number
---@field gFSFlag number
local m = {}


m.vertRepeater = 0
m.r = 0
m.gEEprops = nil
m.solidMtrx = nil
m.gLEprops = nil
m.colr = nil
m.colrDetail = nil
m.colrInd = nil
m.gdLayer = nil
m.gdDetailLayer = nil
m.gdIndLayer = nil
m.gLOProps = nil
m.gLevel = nil
m.gEffectProps = nil
m.gRenderCameraTilePos = nil
m.effectSeed = nil
m.lrSup = nil
m.colrIntensity = nil
m.fruitDensity = nil
m.leafDensity = nil
m.hasFlowers = nil
m.effSide = nil
m.fingerLen = nil
m.fingerSz = nil
m.gCustomEffects = nil
m.gEffects = nil
m.gLastImported = nil
m.mosaicPlantStarts = nil

m.colrDetail = nil
m.lrSup = nil
m.chOp = nil
m.fatOp = nil
m.gradAf = nil
m.effectIn3D = nil
m.gAnyDecals = nil
m.gRotOp = nil
m.slimeFxt = nil
m.DRDarkSlimeFix = nil
m.DRWhite = nil
m.DRPxl = nil
m.DRPxlRect = nil
m.skyRootsFix = nil

m.gLOprops = nil
m.preciseSnap = nil
m.snapToGrid = nil
m.lvlPropOutput = nil
m.gLASTDRAWWASFULLANDMINI = nil

m.gCameraProps = nil
m.SHOWQUADS = nil
m.facH = nil
m.facV = nil
m.showControls = nil

m.gLeProps = nil

m.gCurrentRenderCamera = nil
m.gRenderCameraPixelPos = nil

m.gPrioCam = nil
m.firstCamRepeat = nil

m.newSize = nil
m.extraBufferTiles = nil

m.gLoadedName = nil
m.INT_EXIT = nil
m.INT_EXRD = nil
m.DRInternalList = nil
m.DRFirstTileCat = nil
m.DRLastMatCat = nil
m.RandomMetals_allowed = nil
m.RandomMetals_grabTiles = nil
m.ChaoticStone2_needed = nil
m.DRRandomMetal_needed = nil
m.SmallMachines_grabTiles = nil
m.SmallMachines_forbidden = nil
m.RandomMachines_forbidden = nil
m.RandomMachines_grabTiles = nil
m.RandomMachines2_forbidden = nil
m.RandomMachines2_grabTiles = nil
m.DRBevelColors = nil
m.CommsDrizzle = nil
m.gTiles = nil
m.GL_ptPos = nil
m.GL_drPos = nil
m.GL_keyDict = nil
m.gCustomKeybinds = nil
m.gVersion = nil

m.GL_keyCodeList = nil
m.GL_allKeybinds = nil

m.gTEprops = nil
m.gEEProps = nil
m.lstSpace = nil
m.gEnvEditorProps = nil
m.gDirectionKeys = nil
m.gPEProps = nil
m.gProps = nil
m.gFSLastTm = nil
m.gFSFlag = nil

m.gEnvEditButtons = nil 
m.gLastEnvEditButtons = nil

m.gLOprops = nil 
m.gLightEProps = nil 
m.gLEProps = nil 
m.gEnvEditorProps = nil 
m.gLevel = nil

m.gLEProps = nil 
m.c = nil 
m.keepLooping = nil 
m.gCustomColor = nil 
m.gLoadedName = nil 
m.gLOprops = nil 
m.dptsL = nil 
m.fogDptsL = nil 
m.gCameraProps = nil 
m.gCurrentRenderCamera = nil 
m.gRenderCameraPixelPos = nil 
m.gRenderCameraTilePos = nil 
m.DRPxl = nil 
m.gGradientImages = nil 
m.gAnyDecals = nil 
m.gDecalColors = nil

m.levelName = nil 
m.gLoadedName = nil 
m.gFullRender = nil 
m.gViewRender = nil 
m.gDecalColors = nil 
m.DRFinalImage = nil

m.extraBufferTiles = nil
m.newSize = nil

m.gMassRenderL = nil

m.levelName = nil

m.vertRepeater = nil 
m.r = nil 
m.gEEprops = nil 
m.solidMtrx = nil 
m.gLEprops = nil 
m.colr = nil 
m.colrDetail = nil 
m.colrInd = nil 
m.gdLayer = nil 
m.gdDetailLayer = nil 
m.gdIndLayer = nil 
m.gLOProps = nil 
m.gLevel = nil 
m.gEffectProps = nil 
m.gRenderCameraTilePos = nil 
m.effectSeed = nil 
m.lrSup = nil 
m.chOp = nil 
m.fatOp = nil 
m.gradAf = nil 
m.effectIn3D = nil 
m.gAnyDecals = nil 
m.gRotOp = nil 
m.slimeFxt = nil 
m.DRDarkSlimeFix = nil 
m.DRWhite = nil 
m.DRPxl = nil 
m.DRPxlRect = nil 
m.colrIntensity = nil 
m.skyRootsFix = nil

m.vertRepeater = nil 
m.r = nil 
m.gEEprops = nil 
m.solidMtrx = nil 
m.gLEprops = nil 
m.colr = nil 
m.colrDetail = nil 
m.colrInd = nil 
m.gdLayer = nil 
m.gdDetailLayer = nil 
m.gdIndLayer = nil 
m.gLOProps = nil 
m.gLevel = nil 
m.gEffectProps = nil 
m.gRenderCameraTilePos = nil 
m.effectSeed = nil 
m.lrSup = nil 
m.chOp = nil 
m.fatOp = nil 
m.gradAf = nil 
m.effectIn3D = nil 
m.gAnyDecals = nil 
m.gRotOp = nil 
m.slimeFxt = nil 
m.DRDarkSlimeFix = nil 
m.DRWhite = nil 
m.DRPxl = nil 
m.DRPxlRect = nil 
m.colrIntensity = nil 
m.skyRootsFix = nil
m.daddyCorruptionHoles = nil
m.gCurrentRenderCamera = nil
m.gCameraProps = nil

m.vertRepeater = nil 
m.r = nil 
m.gEEprops = nil 
m.solidMtrx = nil 
m.gLEprops = nil 
m.colr = nil 
m.colrDetail = nil 
m.colrInd = nil 
m.gdLayer = nil 
m.gdDetailLayer = nil 
m.gdIndLayer = nil 
m.gLOProps = nil 
m.gLevel = nil 
m.gEffectProps = nil 
m.gRenderCameraTilePos = nil 
m.effectSeed = nil 
m.lrSup = nil 
m.chOp = nil 
m.fatOp = nil 
m.gradAf = nil 
m.effectIn3D = nil 
m.gAnyDecals = nil 
m.gRotOp = nil 
m.slimeFxt = nil 
m.DRDarkSlimeFix = nil 
m.DRWhite = nil 
m.DRPxl = nil 
m.DRPxlRect = nil 
m.colrIntensity = nil 
m.skyRootsFix = nil
m.gCurrentRenderCamera = nil
m.gCameraProps = nil

m.gLEProps = nil 
m.gLOprops = nil 
m.gFSLastTm = nil 
m.gFSFlag = nil

m.gLEProps = nil 
m.gDirectionKeys = nil 
m.gLOprops = nil 
m.gEnvEditorProps = nil 
m.showControls = nil 
m.gFSLastTm = nil 
m.gFSFlag = nil



return m